/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KALKULATOR;

/**
 *
 * @author Nita
 */
public class desain extends javax.swing.JFrame {
    String angka;
    double jumlah,angka1,angka2, ops;
    int pilih;
    

    /**
     * Creates new form desain
     */
    public desain() {
        initComponents();
        angka="";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hasil = new javax.swing.JTextField();
        persen = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        akar = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        c = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        per = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        min = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        hasil.setEditable(false);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil);
        hasil.setBounds(10, 20, 310, 100);

        persen.setBackground(new java.awt.Color(255, 255, 255));
        persen.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        jPanel1.add(persen);
        persen.setBounds(10, 130, 70, 50);

        tambah.setBackground(new java.awt.Color(255, 255, 255));
        tambah.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(250, 180, 70, 50);

        akar.setBackground(new java.awt.Color(255, 255, 255));
        akar.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });
        jPanel1.add(akar);
        akar.setBounds(90, 130, 70, 50);

        kali.setBackground(new java.awt.Color(255, 255, 255));
        kali.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(170, 180, 70, 50);

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(90, 180, 70, 50);

        bagi.setBackground(new java.awt.Color(255, 255, 255));
        bagi.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(250, 130, 70, 50);

        per.setBackground(new java.awt.Color(255, 255, 255));
        per.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        per.setText("1/x");
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        jPanel1.add(per);
        per.setBounds(170, 130, 70, 50);

        samadengan.setBackground(new java.awt.Color(255, 255, 255));
        samadengan.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        jPanel1.add(samadengan);
        samadengan.setBounds(250, 300, 70, 170);

        kurang.setBackground(new java.awt.Color(255, 255, 255));
        kurang.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(250, 240, 70, 50);

        hapus.setBackground(new java.awt.Color(255, 255, 255));
        hapus.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        hapus.setText("<=");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(10, 180, 70, 50);

        Button9.setBackground(new java.awt.Color(204, 255, 204));
        Button9.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        jPanel1.add(Button9);
        Button9.setBounds(170, 240, 70, 50);

        Button8.setBackground(new java.awt.Color(204, 255, 204));
        Button8.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        jPanel1.add(Button8);
        Button8.setBounds(90, 240, 70, 50);

        Button7.setBackground(new java.awt.Color(204, 255, 204));
        Button7.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        jPanel1.add(Button7);
        Button7.setBounds(10, 240, 70, 50);

        Button6.setBackground(new java.awt.Color(204, 255, 204));
        Button6.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        jPanel1.add(Button6);
        Button6.setBounds(170, 300, 70, 50);

        Button5.setBackground(new java.awt.Color(204, 255, 204));
        Button5.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        jPanel1.add(Button5);
        Button5.setBounds(90, 300, 70, 50);

        Button4.setBackground(new java.awt.Color(204, 255, 204));
        Button4.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        jPanel1.add(Button4);
        Button4.setBounds(10, 300, 70, 50);

        Button3.setBackground(new java.awt.Color(204, 255, 204));
        Button3.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        jPanel1.add(Button3);
        Button3.setBounds(170, 360, 70, 50);

        Button2.setBackground(new java.awt.Color(204, 255, 204));
        Button2.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel1.add(Button2);
        Button2.setBounds(90, 360, 70, 50);

        Button1.setBackground(new java.awt.Color(204, 255, 204));
        Button1.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1);
        Button1.setBounds(10, 360, 70, 50);

        titik.setBackground(new java.awt.Color(204, 255, 204));
        titik.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        jPanel1.add(titik);
        titik.setBounds(170, 420, 70, 50);

        Button0.setBackground(new java.awt.Color(204, 255, 204));
        Button0.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        Button0.setText("0");
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        jPanel1.add(Button0);
        Button0.setBounds(90, 420, 70, 50);

        min.setBackground(new java.awt.Color(204, 255, 204));
        min.setFont(new java.awt.Font("Bodoni Bk BT", 0, 14)); // NOI18N
        min.setText("±");
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        jPanel1.add(min);
        min.setBounds(10, 420, 70, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KALKULATOR/logo telkom.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-180, 140, 830, 710);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 60, 80, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 490);

        setSize(new java.awt.Dimension(345, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        hasil.setText("% ");
        angka="";
        pilih=5;
    }//GEN-LAST:event_persenActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        hasil.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
            //fugsi untuk tombol C
            hasil.setText(null);
            angka1=0.0;
            angka2=0.0;
            jumlah=0.0;
            angka="";
    }//GEN-LAST:event_cActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
         angka+= "9";
            hasil.setText(angka);
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
         angka+= "8";
            hasil.setText(angka);
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
         angka+= "6";
            hasil.setText(angka);
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
         angka+= "5";
            hasil.setText(angka);
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
         angka+= "3";
            hasil.setText(angka);
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
         angka+= "2";
            hasil.setText(angka);
    }//GEN-LAST:event_Button2ActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        // TODO add your handling code here:
            angka += ".";
            hasil.setText(angka);
    }//GEN-LAST:event_titikActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        // TODO add your handling code here:
         angka+= "0";
            hasil.setText(angka);
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
            angka+= "1";
            hasil.setText(angka);
            
    }//GEN-LAST:event_Button1ActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        hasil.setText("+");
        angka ="";
        pilih=1;
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        hasil.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_kurangActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        hasil.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_bagiActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
       
        switch(pilih){
            case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            hasil.setText(angka);
            break;
   case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            hasil.setText(angka);
            break;
   case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            hasil.setText(angka);
            break;
   case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            hasil.setText(angka);
            break;
   case 5:  
          jumlah = angka1/100;
          angka = Double.toString(jumlah);
          hasil.setText(angka);  
          break;
     case 6:      
           jumlah = Math.sqrt(angka1);
           angka = Double.toString(jumlah);
           hasil.setText(angka);
           break;
    case 7:  
          jumlah = 1/angka1;
          angka = Double.toString(jumlah);
          hasil.setText(angka);  
          break;
    case 8:
         angka2 = Double.parseDouble(angka);
         jumlah = angka1 - angka2;
         angka = Double.toString(jumlah);
         hasil.setText(angka);
         
         
         break;
        
            
        }
       hasil.setText(angka);
    }//GEN-LAST:event_samadenganActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        hasil.setText("√");
        angka="";
        pilih=6;
        
    }//GEN-LAST:event_akarActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        hasil.setText("1/x");
        angka="";
        pilih=7;
        
      
        
    }//GEN-LAST:event_perActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
          if(!angka.contains("-"))
              angka = "-" +angka;
          else
              angka = angka.substring(1, angka.length());
          hasil.setText(angka);
       
           
           
    }//GEN-LAST:event_minActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hasilActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        angka = angka.substring(0, angka.length()-1);
        hasil.setText(angka);
       
            
    }//GEN-LAST:event_hapusActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
angka+= "7";
            hasil.setText(angka);    }//GEN-LAST:event_Button7ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
angka+= "4";
            hasil.setText(angka);    }//GEN-LAST:event_Button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new desain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton akar;
    private javax.swing.JButton bagi;
    private javax.swing.JButton c;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton min;
    private javax.swing.JButton per;
    private javax.swing.JButton persen;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton titik;
    // End of variables declaration//GEN-END:variables
}
